import { TaskElement, TaskPriority, TaskStatus } from "./types";

export const MOCK_TASKS: TaskElement[] = [
  {
    id: "task-1",
    title: "Plan product launch.",
    status: TaskStatus.inProgress,
    assignees: ["JS", "AR"],
    dueDate: "2024-12-20",
    priority: TaskPriority.urgent,
    subtasks: [
      {
        id: "subtask-1-1",
        title: "Prepare marketing materials.",
        status: TaskStatus.inProgress,
        assignees: ["JS"],
        dueDate: "2024-12-15",
        priority: TaskPriority.high,
        subtasks: [
          {
            id: "subtask-1-1-1",
            title: "Prepare marketing materials.",
            status: TaskStatus.inProgress,
            assignees: ["JS"],
            dueDate: "2024-12-15",
            priority: TaskPriority.high,
            subtasks: [],
          },
          {
            id: "subtask-1-1-2",
            title: "Prepare marketing materials.",
            status: TaskStatus.inProgress,
            assignees: ["JS"],
            dueDate: "2024-12-15",
            priority: TaskPriority.high,
            subtasks: [],
          },
        ],
      },
      {
        id: "subtask-1-2",
        title: "Set up launch event.",
        status: TaskStatus.todo,
        assignees: ["AR"],
        dueDate: "2024-12-18",
        priority: TaskPriority.high,
        subtasks: [],
      },
    ],
  },
  {
    id: "task-2",
    title: "Team performance review.",
    status: TaskStatus.todo,
    assignees: ["KB", "LT"],
    dueDate: "2024-12-25",
    priority: TaskPriority.normal,
    subtasks: [],
  },
  {
    id: "task-3",
    title: "Develop new feature X.",
    status: TaskStatus.inProgress,
    assignees: ["MW", "EG"],
    dueDate: "2025-01-15",
    priority: TaskPriority.high,
    subtasks: [
      {
        id: "subtask-3-1",
        title: "Code implementation.",
        status: TaskStatus.inProgress,
        assignees: ["MW"],
        dueDate: "2025-01-10",
        priority: TaskPriority.high,
        subtasks: [],
      },
      {
        id: "subtask-3-2",
        title: "Write unit tests.",
        status: TaskStatus.todo,
        assignees: ["EG"],
        dueDate: "2025-01-12",
        priority: TaskPriority.high,
        subtasks: [],
      },
    ],
  },
  {
    id: "task-4",
    title: "Annual budget review.",
    status: TaskStatus.todo,
    assignees: ["JP", "LW"],
    dueDate: "2025-01-05",
    priority: TaskPriority.urgent,
    subtasks: [],
  },
  {
    id: "task-5",
    title: "Customer feedback analysis.",
    status: TaskStatus.completed,
    assignees: ["CM"],
    dueDate: "2024-12-15",
    priority: TaskPriority.normal,
    subtasks: [],
  },
  {
    id: "task-6",
    title: "Redesign company website.",
    status: TaskStatus.inProgress,
    assignees: ["ST", "HW", "JP"],
    dueDate: "2025-02-01",
    priority: TaskPriority.high,
    subtasks: [
      {
        id: "subtask-6-1",
        title: "Wireframe designs.",
        status: TaskStatus.completed,
        assignees: ["ST"],
        dueDate: "2024-12-05",
        priority: TaskPriority.normal,
        subtasks: [],
      },
      {
        id: "subtask-6-2",
        title: "Prototype development.",
        status: TaskStatus.inProgress,
        assignees: ["HW", "JP"],
        dueDate: "2025-01-15",
        priority: TaskPriority.high,
        subtasks: [],
      },
    ],
  },
  {
    id: "task-7",
    title: "Prepare Q1 sales report.",
    status: TaskStatus.completed,
    assignees: ["DW"],
    dueDate: "2024-12-10",
    priority: TaskPriority.low,
    subtasks: [],
  },
  {
    id: "task-8",
    title: "Organize team building event.",
    status: TaskStatus.todo,
    assignees: ["EK", "AW"],
    dueDate: "2024-12-22",
    priority: TaskPriority.normal,
    subtasks: [
      {
        id: "subtask-8-1",
        title: "Book venue.",
        status: TaskStatus.completed,
        assignees: ["EK"],
        dueDate: "2024-12-05",
        priority: TaskPriority.normal,
        subtasks: [],
      },
      {
        id: "subtask-8-2",
        title: "Plan activities.",
        status: TaskStatus.todo,
        assignees: ["AW"],
        dueDate: "2024-12-18",
        priority: TaskPriority.high,
        subtasks: [],
      },
    ],
  },
  {
    id: "task-9",
    title: "Upgrade server infrastructure.",
    status: TaskStatus.inProgress,
    assignees: ["BD", "PL"],
    dueDate: "2025-01-20",
    priority: TaskPriority.urgent,
    subtasks: [],
  },
  {
    id: "task-10",
    title: "Monthly newsletter.",
    status: TaskStatus.todo,
    assignees: ["KF"],
    dueDate: "2024-12-28",
    priority: TaskPriority.low,
    subtasks: [],
  },
];
