import {
  FaAccessibleIcon,
  FaAddressBook,
  FaAddressCard,
  FaAngular,
  FaAppleWhole,
  FaArchway,
  FaArrowRotateLeft,
  FaArrowRotateRight,
  FaArrowsRotate,
  FaAt,
  FaAudioDescription,
  FaBaby,
  FaBabyCarriage,
  FaBackward,
  FaBackwardFast,
  FaBackwardStep,
  FaBacon,
  FaBagShopping,
  FaBan,
  FaBanSmoking,
  FaBarcode,
  FaBarsStaggered,
  FaBaseball,
  FaBasketball,
  FaBasketShopping,
  FaBath,
  FaBatteryEmpty,
  FaBatteryFull,
  FaBatteryHalf,
  FaBatteryQuarter,
  FaBatteryThreeQuarters,
  FaBed,
  FaBell,
  FaBellConcierge,
  FaBellSlash,
  FaBezierCurve,
  FaBicycle,
  FaBitcoin,
  FaBlog,
  FaBluetooth,
  FaBluetoothB,
  FaBone,
  FaBook,
  FaBookAtlas,
  FaBookmark,
  FaBowlingBall,
  FaBox,
  FaBoxArchive,
  FaBoxesStacked,
  FaBreadSlice,
  FaBriefcase,
  FaBroomBall,
  FaBrush,
  FaBtc,
  FaBug,
  FaBuilding,
  FaBullhorn,
  FaBullseye,
  FaBurger,
  FaBus,
  FaBusinessTime,
  FaBusSimple,
  FaCableCar,
  FaCakeCandles,
  FaCalculator,
  FaCalendar,
  FaCalendarCheck,
  FaCalendarDay,
  FaCalendarDays,
  FaCalendarMinus,
  FaCalendarPlus,
  FaCalendarWeek,
  FaCalendarXmark,
  FaCamera,
  FaCameraRetro,
  FaCandyCane,
  FaCar,
  FaCarrot,
  FaCartArrowDown,
  FaCartFlatbed,
  FaCartFlatbedSuitcase,
  FaCartPlus,
  FaCartShopping,
  FaCashRegister,
  FaCertificate,
  FaChalkboard,
  FaChalkboardUser,
  FaChartArea,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaCheese,
  FaChild,
  FaCircle,
  FaCircleDollarToSlot,
  FaCircleExclamation,
  FaCircleHalfStroke,
  FaCircleInfo,
  FaCircleMinus,
  FaCirclePause,
  FaCirclePlay,
  FaCirclePlus,
  FaCircleQuestion,
  FaCircleRadiation,
  FaCircleStop,
  FaCircleUser,
  FaCity,
  FaClipboard,
  FaClipboardCheck,
  FaClipboardList,
  FaClone,
  FaClosedCaptioning,
  FaCloudMeatball,
  FaCode,
  FaCodeBranch,
  FaCoins,
  FaComment,
  FaCommentDollar,
  FaComments,
  FaCommentsDollar,
  FaCommentSlash,
  FaCompass,
  FaCompassDrafting,
  FaCompress,
  FaCookie,
  FaCopy,
  FaCopyright,
  FaCreditCard,
  FaCrop,
  FaCropSimple,
  FaCrosshairs,
  FaCss3Alt,
  FaDatabase,
  FaDesktop,
  FaDiagramProject,
  FaDice,
  FaDiceFive,
  FaDolly,
  FaDoorClosed,
  FaDoorOpen,
  FaDownload,
  FaDrawPolygon,
  FaDroplet,
  FaDropletSlash,
  FaDrum,
  FaDrumSteelpan,
  FaDrumstickBite,
  FaDumbbell,
  FaEarListen,
  FaEarthAfrica,
  FaEarthAmericas,
  FaEarthAsia,
  FaEarthEurope,
  FaEgg,
  FaEject,
  FaEnvelope,
  FaEnvelopeOpen,
  FaEnvelopeOpenText,
  FaEnvelopesBulk,
  FaEraser,
  FaEthereum,
  FaEthernet,
  FaExclamation,
  FaExpand,
  FaEye,
  FaEyeDropper,
  FaEyeSlash,
  FaFacebook,
  FaFaceFrown,
  FaFaceMeh,
  FaFaceSmile,
  FaFax,
  FaFile,
  FaFileAudio,
  FaFileCode,
  FaFileInvoice,
  FaFileInvoiceDollar,
  FaFileLines,
  FaFileVideo,
  FaFill,
  FaFillDrip,
  FaFilm,
  FaFilter,
  FaFilterCircleDollar,
  FaFireExtinguisher,
  FaFireFlameCurved,
  FaFireFlameSimple,
  FaFish,
  FaFloppyDisk,
  FaFolder,
  FaFolderMinus,
  FaFolderOpen,
  FaFolderPlus,
  FaFootball,
  FaForward,
  FaForwardFast,
  FaForwardStep,
  FaFutbol,
  FaGasPump,
  FaGem,
  FaGift,
  FaGlasses,
  FaGlobe,
  FaGolfBallTee,
  FaGoogleWallet,
  FaGuitar,
  FaHandHoldingDollar,
  FaHandsAslInterpreting,
  FaHandshake,
  FaHardDrive,
  FaHashtag,
  FaHeadphones,
  FaHeadphonesSimple,
  FaHeart,
  FaHeartPulse,
  FaHelmetSafety,
  FaHighlighter,
  FaHockeyPuck,
  FaHotdog,
  FaHotel,
  FaHotTubPerson,
  FaIceCream,
  FaIcons,
  FaIdBadge,
  FaIdCard,
  FaIdCardClip,
  FaImage,
  FaImagePortrait,
  FaImages,
  FaInbox,
  FaIndustry,
  FaInfinity,
  FaInfo,
  FaInstagram,
  FaJs,
  FaKey,
  FaKeyboard,
  FaLandmark,
  FaLanguage,
  FaLaptop,
  FaLaptopCode,
  FaLayerGroup,
  FaLemon,
  FaLightbulb,
  FaLinkedin,
  FaListCheck,
  FaLocationDot,
  FaLocationPin,
  FaLock,
  FaLockOpen,
  FaMagnifyingGlassDollar,
  FaMagnifyingGlassLocation,
  FaMap,
  FaMapLocation,
  FaMapLocationDot,
  FaMarker,
  FaMartiniGlass,
  FaMartiniGlassCitrus,
  FaMartiniGlassEmpty,
  FaMaximize,
  FaMemory,
  FaMessage,
  FaMicrochip,
  FaMicrophone,
  FaMicrophoneLines,
  FaMicrophoneLinesSlash,
  FaMicrophoneSlash,
  FaMinimize,
  FaMinus,
  FaMobile,
  FaMobileButton,
  FaMoneyBill,
  FaMoneyBill1,
  FaMoneyBill1Wave,
  FaMoneyBillWave,
  FaMoneyCheck,
  FaMoneyCheckDollar,
  FaMonument,
  FaMugSaucer,
  FaMusic,
  FaNapster,
  FaNewspaper,
  FaNoteSticky,
  FaObjectGroup,
  FaObjectUngroup,
  FaPaintbrush,
  FaPaintRoller,
  FaPalette,
  FaPallet,
  FaPaperclip,
  FaPaperPlane,
  FaParagraph,
  FaPassport,
  FaPaste,
  FaPause,
  FaPen,
  FaPencil,
  FaPenClip,
  FaPenFancy,
  FaPenNib,
  FaPenRuler,
  FaPenToSquare,
  FaPeopleCarryBox,
  FaPepperHot,
  FaPercent,
  FaPerson,
  FaPersonBiking,
  FaPersonBooth,
  FaPersonDress,
  FaPersonHiking,
  FaPersonPraying,
  FaPersonRunning,
  FaPersonSkating,
  FaPersonSkiing,
  FaPersonSkiingNordic,
  FaPersonSnowboarding,
  FaPersonSwimming,
  FaPersonWalking,
  FaPersonWalkingWithCane,
  FaPhone,
  FaPhoneFlip,
  FaPhoneSlash,
  FaPhoneVolume,
  FaPhotoFilm,
  FaPiggyBank,
  FaPinterest,
  FaPizzaSlice,
  FaPlane,
  FaPlaneArrival,
  FaPlaneDeparture,
  FaPlay,
  FaPlug,
  FaPlus,
  FaPodcast,
  FaPoo,
  FaPowerOff,
  FaPrint,
  FaQrcode,
  FaQuestion,
  FaQuoteLeft,
  FaQuoteRight,
  FaRadiation,
  FaReact,
  FaReceipt,
  FaRectangleAd,
  FaRectangleXmark,
  FaRegistered,
  FaRegWindowRestore,
  FaRestroom,
  FaRetweet,
  FaRightFromBracket,
  FaRightToBracket,
  FaRotate,
  FaRotateLeft,
  FaRotateRight,
  FaRss,
  FaRulerCombined,
  FaRulerHorizontal,
  FaRulerVertical,
  FaSailboat,
  FaSatellite,
  FaSatelliteDish,
  FaScaleBalanced,
  FaScaleUnbalanced,
  FaScaleUnbalancedFlip,
  FaScissors,
  FaSdCard,
  FaSeedling,
  FaServer,
  FaShare,
  FaShareFromSquare,
  FaShareNodes,
  FaShieldHalved,
  FaShip,
  FaShoePrints,
  FaShower,
  FaShuffle,
  FaSignal,
  FaSimCard,
  FaSitemap,
  FaSkullCrossbones,
  FaSliders,
  FaSmoking,
  FaSnapchat,
  FaSnowflake,
  FaSocks,
  FaSoundcloud,
  FaSpa,
  FaSplotch,
  FaSpotify,
  FaSprayCan,
  FaSquareEnvelope,
  FaSquareMinus,
  FaSquareParking,
  FaSquarePen,
  FaSquarePhone,
  FaSquarePhoneFlip,
  FaSquarePlus,
  FaSquarePollHorizontal,
  FaSquarePollVertical,
  FaSquareRss,
  FaStamp,
  FaStar,
  FaStarHalf,
  FaStarHalfStroke,
  FaStop,
  FaStreetView,
  FaStripe,
  FaStripeS,
  FaStroopwafel,
  FaSuitcase,
  FaSuitcaseRolling,
  FaSwatchbook,
  FaTable,
  FaTableColumns,
  FaTablet,
  FaTableTennisPaddleBall,
  FaTabletScreenButton,
  FaTag,
  FaTags,
  FaTaxi,
  FaTelegram,
  FaTemperatureEmpty,
  FaTemperatureFull,
  FaTemperatureHalf,
  FaTemperatureQuarter,
  FaTemperatureThreeQuarters,
  FaTerminal,
  FaThumbsDown,
  FaThumbsUp,
  FaThumbtack,
  FaToggleOff,
  FaToggleOn,
  FaTowerBroadcast,
  FaTrademark,
  FaTriangleExclamation,
  FaTrophy,
  FaTruck,
  FaTruckFast,
  FaTty,
  FaTv,
  FaTwitter,
  FaUmbrellaBeach,
  FaUnlock,
  FaUnlockKeyhole,
  FaUpload,
  FaUser,
  FaUserAstronaut,
  FaUserCheck,
  FaUserClock,
  FaUserDoctor,
  FaUserGear,
  FaUserGraduate,
  FaUserGroup,
  FaUserInjured,
  FaUserLarge,
  FaUserLargeSlash,
  FaUserLock,
  FaUserMinus,
  FaUserNinja,
  FaUserNurse,
  FaUserPen,
  FaUserPlus,
  FaUsers,
  FaUserSecret,
  FaUsersGear,
  FaUserShield,
  FaUserSlash,
  FaUserTag,
  FaUserTie,
  FaUserXmark,
  FaUtensils,
  FaVanShuttle,
  FaVectorSquare,
  FaVideo,
  FaVideoSlash,
  FaVoicemail,
  FaVolleyball,
  FaVolumeHigh,
  FaVolumeLow,
  FaVolumeOff,
  FaVolumeXmark,
  FaVuejs,
  FaWallet,
  FaWandMagic,
  FaWarehouse,
  FaWaterLadder,
  FaWheelchair,
  FaWifi,
  FaWindowMaximize,
  FaWindowMinimize,
  FaWineGlass,
  FaWineGlassEmpty,
  FaYoutube,
} from "react-icons/fa6";

export const AddIcons: Record<
  string,
  React.ComponentType<React.SVGProps<SVGSVGElement>>
> = {
  AddressBook: FaAddressBook,
  Bug: FaBug,
  Desktop: FaDesktop,
  Globe: FaGlobe,
  CalendarDays: FaCalendarDays,
  User: FaUser,
  Landmark: FaLandmark,
  ClipboardList: FaClipboardList,
  MugSaucer: FaMugSaucer,
  Eye: FaEye,
  PowerOff: FaPowerOff,
  Folder: FaFolder,
  FileLines: FaFileLines,
  PizzaSlice: FaPizzaSlice,
  Wifi: FaWifi,
  Camera: FaCamera,
  Comment: FaComment,
  Envelope: FaEnvelope,
  Gift: FaGift,
  Info: FaInfo,
  Image: FaImage,
  Key: FaKey,
  Lock: FaLock,
  Lightbulb: FaLightbulb,
  Music: FaMusic,
  Paperclip: FaPaperclip,
  Plus: FaPlus,
  ShareNodes: FaShareNodes,
  CircleUser: FaCircleUser,
  UserSecret: FaUserSecret,
  Snowflake: FaSnowflake,
  AccessibleIcon: FaAccessibleIcon,
  RectangleAd: FaRectangleAd,
  AddressCard: FaAddressCard,
  CircleHalfStroke: FaCircleHalfStroke,
  HandsAslInterpreting: FaHandsAslInterpreting,
  Angular: FaAngular,
  AppleWhole: FaAppleWhole,
  BoxArchive: FaBoxArchive,
  Archway: FaArchway,
  EarListen: FaEarListen,
  At: FaAt,
  BookAtlas: FaBookAtlas,
  AudioDescription: FaAudioDescription,
  Baby: FaBaby,
  BabyCarriage: FaBabyCarriage,
  Backward: FaBackward,
  Bacon: FaBacon,
  ScaleBalanced: FaScaleBalanced,
  ScaleUnbalanced: FaScaleUnbalanced,
  ScaleUnbalancedFlip: FaScaleUnbalancedFlip,
  Ban: FaBan,
  Barcode: FaBarcode,
  Baseball: FaBaseball,
  Basketball: FaBasketball,
  Bath: FaBath,
  BatteryEmpty: FaBatteryEmpty,
  BatteryFull: FaBatteryFull,
  BatteryHalf: FaBatteryHalf,
  BatteryQuarter: FaBatteryQuarter,
  BatteryThreeQuarters: FaBatteryThreeQuarters,
  Bed: FaBed,
  Bell: FaBell,
  BellSlash: FaBellSlash,
  BezierCurve: FaBezierCurve,
  Bicycle: FaBicycle,
  PersonBiking: FaPersonBiking,
  CakeCandles: FaCakeCandles,
  Bitcoin: FaBitcoin,
  PersonWalkingWithCane: FaPersonWalkingWithCane,
  Blog: FaBlog,
  Bluetooth: FaBluetooth,
  BluetoothB: FaBluetoothB,
  Bone: FaBone,
  Book: FaBook,
  Bookmark: FaBookmark,
  BowlingBall: FaBowlingBall,
  Box: FaBox,
  BoxesStacked: FaBoxesStacked,
  BreadSlice: FaBreadSlice,
  Briefcase: FaBriefcase,
  TowerBroadcast: FaTowerBroadcast,
  Brush: FaBrush,
  Btc: FaBtc,
  Building: FaBuilding,
  Bullhorn: FaBullhorn,
  Bullseye: FaBullseye,
  FireFlameSimple: FaFireFlameSimple,
  Bus: FaBus,
  BusSimple: FaBusSimple,
  BusinessTime: FaBusinessTime,
  Calculator: FaCalculator,
  Calendar: FaCalendar,
  CalendarCheck: FaCalendarCheck,
  CalendarDay: FaCalendarDay,
  CalendarMinus: FaCalendarMinus,
  CalendarPlus: FaCalendarPlus,
  CalendarXmark: FaCalendarXmark,
  CalendarWeek: FaCalendarWeek,
  CameraRetro: FaCameraRetro,
  CandyCane: FaCandyCane,
  Car: FaCar,
  Carrot: FaCarrot,
  CartArrowDown: FaCartArrowDown,
  CartPlus: FaCartPlus,
  CashRegister: FaCashRegister,
  Certificate: FaCertificate,
  Chalkboard: FaChalkboard,
  ChalkboardUser: FaChalkboardUser,
  ChartArea: FaChartArea,
  ChartBar: FaChartBar,
  ChartLine: FaChartLine,
  ChartPie: FaChartPie,
  Cheese: FaCheese,
  Child: FaChild,
  Circle: FaCircle,
  City: FaCity,
  Clipboard: FaClipboard,
  ClipboardCheck: FaClipboardCheck,
  Clone: FaClone,
  ClosedCaptioning: FaClosedCaptioning,
  CloudMeatball: FaCloudMeatball,
  MartiniGlassCitrus: FaMartiniGlassCitrus,
  Code: FaCode,
  CodeBranch: FaCodeBranch,
  Coins: FaCoins,
  TableColumns: FaTableColumns,
  Message: FaMessage,
  CommentDollar: FaCommentDollar,
  CommentSlash: FaCommentSlash,
  Comments: FaComments,
  CommentsDollar: FaCommentsDollar,
  Compass: FaCompass,
  Compress: FaCompress,
  Minimize: FaMinimize,
  BellConcierge: FaBellConcierge,
  Cookie: FaCookie,
  Copy: FaCopy,
  Copyright: FaCopyright,
  CreditCard: FaCreditCard,
  Crop: FaCrop,
  CropSimple: FaCropSimple,
  Crosshairs: FaCrosshairs,
  Css3Alt: FaCss3Alt,
  Scissors: FaScissors,
  Database: FaDatabase,
  Dice: FaDice,
  DiceFive: FaDiceFive,
  Dolly: FaDolly,
  CartFlatbed: FaCartFlatbed,
  CircleDollarToSlot: FaCircleDollarToSlot,
  DoorClosed: FaDoorClosed,
  DoorOpen: FaDoorOpen,
  Download: FaDownload,
  CompassDrafting: FaCompassDrafting,
  DrawPolygon: FaDrawPolygon,
  Drum: FaDrum,
  DrumSteelpan: FaDrumSteelpan,
  DrumstickBite: FaDrumstickBite,
  Dumbbell: FaDumbbell,
  PenToSquare: FaPenToSquare,
  Egg: FaEgg,
  Eject: FaEject,
  EnvelopeOpen: FaEnvelopeOpen,
  EnvelopeOpenText: FaEnvelopeOpenText,
  SquareEnvelope: FaSquareEnvelope,
  Eraser: FaEraser,
  Ethereum: FaEthereum,
  Ethernet: FaEthernet,
  Exclamation: FaExclamation,
  CircleExclamation: FaCircleExclamation,
  TriangleExclamation: FaTriangleExclamation,
  Expand: FaExpand,
  Maximize: FaMaximize,
  EyeDropper: FaEyeDropper,
  EyeSlash: FaEyeSlash,
  Facebook: FaFacebook,
  BackwardFast: FaBackwardFast,
  ForwardFast: FaForwardFast,
  Fax: FaFax,
  PersonDress: FaPersonDress,
  File: FaFile,
  FileAudio: FaFileAudio,
  FileCode: FaFileCode,
  FileInvoice: FaFileInvoice,
  FileInvoiceDollar: FaFileInvoiceDollar,
  FileVideo: FaFileVideo,
  Fill: FaFill,
  FillDrip: FaFillDrip,
  Film: FaFilm,
  Filter: FaFilter,
  FireFlameCurved: FaFireFlameCurved,
  FireExtinguisher: FaFireExtinguisher,
  Fish: FaFish,
  FolderMinus: FaFolderMinus,
  FolderOpen: FaFolderOpen,
  FolderPlus: FaFolderPlus,
  Football: FaFootball,
  Forward: FaForward,
  FaceFrown: FaFaceFrown,
  FilterCircleDollar: FaFilterCircleDollar,
  Futbol: FaFutbol,
  GasPump: FaGasPump,
  Gem: FaGem,
  MartiniGlassEmpty: FaMartiniGlassEmpty,
  MartiniGlass: FaMartiniGlass,
  Glasses: FaGlasses,
  EarthAfrica: FaEarthAfrica,
  EarthAmericas: FaEarthAmericas,
  EarthAsia: FaEarthAsia,
  EarthEurope: FaEarthEurope,
  GolfBallTee: FaGolfBallTee,
  GoogleWallet: FaGoogleWallet,
  Guitar: FaGuitar,
  Burger: FaBurger,
  HandHoldingDollar: FaHandHoldingDollar,
  Handshake: FaHandshake,
  HelmetSafety: FaHelmetSafety,
  Hashtag: FaHashtag,
  HardDrive: FaHardDrive,
  Headphones: FaHeadphones,
  HeadphonesSimple: FaHeadphonesSimple,
  Heart: FaHeart,
  HeartPulse: FaHeartPulse,
  Highlighter: FaHighlighter,
  PersonHiking: FaPersonHiking,
  HockeyPuck: FaHockeyPuck,
  HotTubPerson: FaHotTubPerson,
  Hotdog: FaHotdog,
  Hotel: FaHotel,
  Js: FaJs,
  IceCream: FaIceCream,
  Icons: FaIcons,
  IdBadge: FaIdBadge,
  IdCard: FaIdCard,
  IdCardClip: FaIdCardClip,
  Images: FaImages,
  Inbox: FaInbox,
  Industry: FaIndustry,
  Infinity: FaInfinity,
  CircleInfo: FaCircleInfo,
  Instagram: FaInstagram,
  Keyboard: FaKeyboard,
  Language: FaLanguage,
  Laptop: FaLaptop,
  LaptopCode: FaLaptopCode,
  LayerGroup: FaLayerGroup,
  Lemon: FaLemon,
  Linkedin: FaLinkedin,
  LockOpen: FaLockOpen,
  CartFlatbedSuitcase: FaCartFlatbedSuitcase,
  WandMagic: FaWandMagic,
  EnvelopesBulk: FaEnvelopesBulk,
  Person: FaPerson,
  Map: FaMap,
  MapLocation: FaMapLocation,
  MapLocationDot: FaMapLocationDot,
  LocationPin: FaLocationPin,
  LocationDot: FaLocationDot,
  Marker: FaMarker,
  FaceMeh: FaFaceMeh,
  Memory: FaMemory,
  Microchip: FaMicrochip,
  Microphone: FaMicrophone,
  MicrophoneLines: FaMicrophoneLines,
  MicrophoneLinesSlash: FaMicrophoneLinesSlash,
  MicrophoneSlash: FaMicrophoneSlash,
  Minus: FaMinus,
  CircleMinus: FaCircleMinus,
  SquareMinus: FaSquareMinus,
  Mobile: FaMobile,
  MobileButton: FaMobileButton,
  MoneyBill: FaMoneyBill,
  MoneyBill1: FaMoneyBill1,
  MoneyBillWave: FaMoneyBillWave,
  MoneyBill1Wave: FaMoneyBill1Wave,
  MoneyCheck: FaMoneyCheck,
  MoneyCheckDollar: FaMoneyCheckDollar,
  Monument: FaMonument,
  Napster: FaNapster,
  Newspaper: FaNewspaper,
  ObjectGroup: FaObjectGroup,
  ObjectUngroup: FaObjectUngroup,
  Paintbrush: FaPaintbrush,
  PaintRoller: FaPaintRoller,
  Palette: FaPalette,
  Pallet: FaPallet,
  PaperPlane: FaPaperPlane,
  Paragraph: FaParagraph,
  SquareParking: FaSquareParking,
  Passport: FaPassport,
  Paste: FaPaste,
  Pause: FaPause,
  CirclePause: FaCirclePause,
  Pen: FaPen,
  PenClip: FaPenClip,
  PenFancy: FaPenFancy,
  PenNib: FaPenNib,
  SquarePen: FaSquarePen,
  Pencil: FaPencil,
  PenRuler: FaPenRuler,
  PeopleCarryBox: FaPeopleCarryBox,
  PepperHot: FaPepperHot,
  Percent: FaPercent,
  PersonBooth: FaPersonBooth,
  Pinterest: FaPinterest,
  Phone: FaPhone,
  PhoneFlip: FaPhoneFlip,
  PhoneSlash: FaPhoneSlash,
  SquarePhone: FaSquarePhone,
  SquarePhoneFlip: FaSquarePhoneFlip,
  PhoneVolume: FaPhoneVolume,
  PhotoFilm: FaPhotoFilm,
  PiggyBank: FaPiggyBank,
  Plane: FaPlane,
  PlaneArrival: FaPlaneArrival,
  PlaneDeparture: FaPlaneDeparture,
  Play: FaPlay,
  CirclePlay: FaCirclePlay,
  Plug: FaPlug,
  CirclePlus: FaCirclePlus,
  SquarePlus: FaSquarePlus,
  Podcast: FaPodcast,
  SquarePollVertical: FaSquarePollVertical,
  SquarePollHorizontal: FaSquarePollHorizontal,
  Poo: FaPoo,
  ImagePortrait: FaImagePortrait,
  PersonPraying: FaPersonPraying,
  Print: FaPrint,
  DiagramProject: FaDiagramProject,
  React: FaReact,
  Qrcode: FaQrcode,
  Question: FaQuestion,
  CircleQuestion: FaCircleQuestion,
  BroomBall: FaBroomBall,
  QuoteLeft: FaQuoteLeft,
  QuoteRight: FaQuoteRight,
  Radiation: FaRadiation,
  CircleRadiation: FaCircleRadiation,
  Shuffle: FaShuffle,
  Receipt: FaReceipt,
  ArrowRotateRight: FaArrowRotateRight,
  RotateRight: FaRotateRight,
  Registered: FaRegistered,
  Restroom: FaRestroom,
  Retweet: FaRetweet,
  Rss: FaRss,
  SquareRss: FaSquareRss,
  RulerCombined: FaRulerCombined,
  RulerHorizontal: FaRulerHorizontal,
  RulerVertical: FaRulerVertical,
  PersonRunning: FaPersonRunning,
  Satellite: FaSatellite,
  SatelliteDish: FaSatelliteDish,
  FloppyDisk: FaFloppyDisk,
  SdCard: FaSdCard,
  MagnifyingGlassDollar: FaMagnifyingGlassDollar,
  MagnifyingGlassLocation: FaMagnifyingGlassLocation,
  Seedling: FaSeedling,
  Server: FaServer,
  Share: FaShare,
  ShareFromSquare: FaShareFromSquare,
  ShieldHalved: FaShieldHalved,
  TruckFast: FaTruckFast,
  ShoePrints: FaShoePrints,
  BagShopping: FaBagShopping,
  BasketShopping: FaBasketShopping,
  CartShopping: FaCartShopping,
  Shower: FaShower,
  VanShuttle: FaVanShuttle,
  RightToBracket: FaRightToBracket,
  RightFromBracket: FaRightFromBracket,
  Signal: FaSignal,
  SimCard: FaSimCard,
  Sitemap: FaSitemap,
  PersonSkating: FaPersonSkating,
  PersonSkiing: FaPersonSkiing,
  PersonSkiingNordic: FaPersonSkiingNordic,
  SkullCrossbones: FaSkullCrossbones,
  Sliders: FaSliders,
  FaceSmile: FaFaceSmile,
  Smoking: FaSmoking,
  BanSmoking: FaBanSmoking,
  Snapchat: FaSnapchat,
  PersonSnowboarding: FaPersonSnowboarding,
  Socks: FaSocks,
  Soundcloud: FaSoundcloud,
  Spa: FaSpa,
  Splotch: FaSplotch,
  Spotify: FaSpotify,
  SprayCan: FaSprayCan,
  Stamp: FaStamp,
  Star: FaStar,
  StarHalf: FaStarHalf,
  StarHalfStroke: FaStarHalfStroke,
  BackwardStep: FaBackwardStep,
  ForwardStep: FaForwardStep,
  NoteSticky: FaNoteSticky,
  Stop: FaStop,
  CircleStop: FaCircleStop,
  BarsStaggered: FaBarsStaggered,
  StreetView: FaStreetView,
  Stripe: FaStripe,
  StripeS: FaStripeS,
  Stroopwafel: FaStroopwafel,
  Suitcase: FaSuitcase,
  SuitcaseRolling: FaSuitcaseRolling,
  Swatchbook: FaSwatchbook,
  PersonSwimming: FaPersonSwimming,
  WaterLadder: FaWaterLadder,
  ArrowsRotate: FaArrowsRotate,
  Rotate: FaRotate,
  Table: FaTable,
  TableTennisPaddleBall: FaTableTennisPaddleBall,
  Tablet: FaTablet,
  TabletScreenButton: FaTabletScreenButton,
  Tag: FaTag,
  Tags: FaTags,
  ListCheck: FaListCheck,
  Taxi: FaTaxi,
  Telegram: FaTelegram,
  Terminal: FaTerminal,
  TemperatureEmpty: FaTemperatureEmpty,
  TemperatureFull: FaTemperatureFull,
  TemperatureHalf: FaTemperatureHalf,
  TemperatureQuarter: FaTemperatureQuarter,
  TemperatureThreeQuarters: FaTemperatureThreeQuarters,
  ThumbsDown: FaThumbsDown,
  ThumbsUp: FaThumbsUp,
  Thumbtack: FaThumbtack,
  Droplet: FaDroplet,
  DropletSlash: FaDropletSlash,
  ToggleOff: FaToggleOff,
  ToggleOn: FaToggleOn,
  Trademark: FaTrademark,
  CableCar: FaCableCar,
  Trophy: FaTrophy,
  Truck: FaTruck,
  Tty: FaTty,
  Tv: FaTv,
  Twitter: FaTwitter,
  UmbrellaBeach: FaUmbrellaBeach,
  ArrowRotateLeft: FaArrowRotateLeft,
  RotateLeft: FaRotateLeft,
  Unlock: FaUnlock,
  UnlockKeyhole: FaUnlockKeyhole,
  Upload: FaUpload,
  UserLarge: FaUserLarge,
  UserLargeSlash: FaUserLargeSlash,
  UserAstronaut: FaUserAstronaut,
  UserCheck: FaUserCheck,
  UserClock: FaUserClock,
  UserGear: FaUserGear,
  UserPen: FaUserPen,
  UserGroup: FaUserGroup,
  UserGraduate: FaUserGraduate,
  UserInjured: FaUserInjured,
  UserLock: FaUserLock,
  Ship: FaShip,
  Sailboat: FaSailboat,
  UserDoctor: FaUserDoctor,
  UserMinus: FaUserMinus,
  UserNinja: FaUserNinja,
  UserNurse: FaUserNurse,
  UserPlus: FaUserPlus,
  UserShield: FaUserShield,
  UserSlash: FaUserSlash,
  UserTag: FaUserTag,
  UserTie: FaUserTie,
  UserXmark: FaUserXmark,
  Users: FaUsers,
  UsersGear: FaUsersGear,
  Utensils: FaUtensils,
  VectorSquare: FaVectorSquare,
  Video: FaVideo,
  VideoSlash: FaVideoSlash,
  Voicemail: FaVoicemail,
  Volleyball: FaVolleyball,
  VolumeLow: FaVolumeLow,
  VolumeXmark: FaVolumeXmark,
  VolumeOff: FaVolumeOff,
  VolumeHigh: FaVolumeHigh,
  Vuejs: FaVuejs,
  PersonWalking: FaPersonWalking,
  Wallet: FaWallet,
  Warehouse: FaWarehouse,
  Wheelchair: FaWheelchair,
  RectangleXmark: FaRectangleXmark,
  WindowMaximize: FaWindowMaximize,
  WindowMinimize: FaWindowMinimize,
  RegWindowRestore: FaRegWindowRestore,
  WineGlass: FaWineGlass,
  WineGlassEmpty: FaWineGlassEmpty,
  Youtube: FaYoutube,
};
